"""
bridgecad_qa.reports — Generate HTML QA compliance report.
"""
from __future__ import annotations
from pathlib import Path
from typing import Any


def generate_html_report(
    report: Any,
    output_path: str | Path,
    project: Any | None = None,
) -> Path:
    """Write a styled HTML QA report to *output_path*."""
    from .compliance import score as _score

    comp  = _score(report)
    p     = Path(output_path)
    p.parent.mkdir(parents=True, exist_ok=True)

    pm = project.project_master if project else None
    proj_title  = str(getattr(pm, "project_title", "Bridge Project") or "Bridge Project")
    bridge_name = str(getattr(pm, "bridge_name",  "")  or "")
    chainage    = str(float(getattr(pm, "chainage_km", 0) or 0))

    colour = "#27ae60" if comp.grade in ("A+","A") else \
             "#f39c12" if comp.grade in ("B","C")  else "#e74c3c"

    rows_html = ""
    for f in sorted(report.findings, key=lambda x: (x.passed, x.check_id)):
        sev   = f.severity.name if hasattr(f.severity, "name") else str(f.severity)
        icon  = "✅" if f.passed else ("🔴" if "CRITICAL" in sev else "🟡")
        style = "" if f.passed else ('background:#fff3cd' if "WARNING" in sev else 'background:#f8d7da')
        rows_html += (
            f"<tr style='{style}'>"
            f"<td>{icon}</td>"
            f"<td><code>{f.check_id}</code></td>"
            f"<td>{sev}</td>"
            f"<td>{f.description}</td>"
            f"<td style='color:{'green' if f.passed else 'red'}'>"
            f"{'PASS' if f.passed else 'FAIL'}</td>"
            f"<td>{f.message or '—'}</td>"
            f"</tr>\n"
        )

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>QA Report — {proj_title}</title>
<style>
  body {{font-family:Arial,sans-serif;margin:20px;color:#333}}
  h1   {{color:#1a237e}}
  .score-box {{display:inline-block;padding:20px 40px;border-radius:12px;
               background:{colour};color:#fff;font-size:2.5em;font-weight:bold;margin:10px}}
  .summary {{display:flex;gap:20px;margin:20px 0;flex-wrap:wrap}}
  .card {{background:#f5f5f5;border-radius:8px;padding:15px 25px;min-width:140px}}
  .card h3 {{margin:0 0 5px;font-size:0.9em;color:#666}}
  .card p  {{margin:0;font-size:1.6em;font-weight:bold}}
  table {{border-collapse:collapse;width:100%;margin-top:20px}}
  th,td {{border:1px solid #ddd;padding:8px 12px;text-align:left;font-size:0.9em}}
  th    {{background:#1a237e;color:#fff}}
  tr:hover {{background:#f0f4ff}}
</style>
</head>
<body>
<h1>🏗️ BridgeCAD QA Compliance Report</h1>
<p><strong>Project:</strong> {proj_title}<br>
   <strong>Bridge:</strong>  {bridge_name}<br>
   <strong>Chainage:</strong> {chainage} km</p>

<div class="summary">
  <div><div class="score-box">{comp.overall}/100</div>
       <p><strong>Grade {comp.grade}</strong></p></div>
  <div class="card"><h3>IRC:5 (Hydraulic)</h3><p>{comp.irc05}/100</p></div>
  <div class="card"><h3>IRC:112 (Structural)</h3><p>{comp.irc21}/100</p></div>
  <div class="card"><h3>IRC SP:55 (Drawing)</h3><p>{comp.irc_sp55}/100</p></div>
  <div class="card"><h3>Critical Fails</h3>
       <p style="color:{'red' if comp.critical_fails else 'green'}">{comp.critical_fails}</p></div>
  <div class="card"><h3>Warnings</h3>
       <p style="color:{'orange' if comp.warning_fails else 'green'}">{comp.warning_fails}</p></div>
  <div class="card"><h3>Total Checks</h3><p>{len(report.findings)}</p></div>
</div>

<h2>Check Results</h2>
<table>
  <tr><th></th><th>ID</th><th>Severity</th><th>Description</th>
      <th>Result</th><th>Message</th></tr>
{rows_html}
</table>

<p style="color:#999;font-size:0.8em;margin-top:30px">
Generated by BridgeCAD Enterprise Suite v0.1.0 | IRC SP:55-2019 compliance framework
</p>
</body>
</html>"""

    p.write_text(html, encoding="utf-8")
    return p


__all__ = ["generate_html_report"]
